kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ekosystem-readonly
  namespace: ekosystem
subjects:
- kind: User
  name: ekosystem-readonly
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
